services:
    cabot.floconsdeneige.listener:
        class: cabot\floconsdeneige\event\listener
        arguments:
            - '@request'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
